// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/answers": {
            "get": {
                "description": "возвращает список вопросов с вариантами ответов",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "тесты"
                ],
                "summary": "возвращает список вопросов с вариантами ответов",
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.ResponseQuestion"
                            }
                        }
                    }
                }
            }
        },
        "/check": {
            "post": {
                "description": "Принимает список выбранных пользователем ответов (questionCode + answerCodes) и возвращает результат проверки",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "тесты"
                ],
                "summary": "Проверка ответов пользователя",
                "parameters": [
                    {
                        "description": "Ответы пользователя",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.UserAnswer"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.CheckResult"
                            }
                        }
                    },
                    "400": {
                        "description": "Ошибка запроса",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/quest": {
            "get": {
                "description": "Возвращает случайно выбранный вопрос из базы",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "тесты"
                ],
                "summary": "Случайный вопрос",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Quest"
                        }
                    }
                }
            }
        },
        "/thema/{code}": {
            "get": {
                "description": "Возвращает текстовый блок (InfoBlock) по теме",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "темы"
                ],
                "summary": "Полная информация о теме",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Код темы",
                        "name": "code",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Текст темы",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Тема не найдена",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/thema/{code}/questions": {
            "get": {
                "description": "Возвращает список вопросов для указанной темы без вариантов ответов",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "тесты"
                ],
                "summary": "Список вопросов по теме",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Код темы",
                        "name": "code",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Question"
                            }
                        }
                    },
                    "404": {
                        "description": "Вопросы для темы не найдены",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/themas": {
            "get": {
                "description": "Возвращает краткую информацию по всем темам курса",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "темы"
                ],
                "summary": "Список тем",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Thema"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.Answer": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "models.AnswerVariant": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "isRight": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "models.CheckResult": {
            "type": "object",
            "properties": {
                "isCorrect": {
                    "type": "boolean"
                },
                "questionCode": {
                    "type": "string"
                },
                "rightAnswerCode": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "userAnswerCode": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "models.NoiseSource": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "models.Quest": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "imagePNG": {
                    "type": "string"
                },
                "noise": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.NoiseSource"
                    }
                }
            }
        },
        "models.Question": {
            "type": "object",
            "properties": {
                "answers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.AnswerVariant"
                    }
                },
                "code": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "models.ResponseQuestion": {
            "type": "object",
            "properties": {
                "answers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Answer"
                    }
                },
                "code": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "models.StatusThema": {
            "type": "string",
            "enum": [
                "open",
                "current",
                "completed"
            ],
            "x-enum-varnames": [
                "StatusThemaOpen",
                "StatusThemaCurrent",
                "StatusThemaCompleted"
            ]
        },
        "models.Thema": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/models.StatusThema"
                }
            }
        },
        "models.UserAnswer": {
            "type": "object",
            "properties": {
                "answerCodes": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "question_code": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:3000",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "My Go API",
	Description:      "This is a sample server for a Go API.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
